[WIP] - Chore/set up project
junan/nimble-survey pull request #1
Opened 2020-11-13 11:21 UTC by junan

2020-11-16 11:33 UTC, carryall requested changes

2020-11-16 11:33 UTC, carryall commented on e2e/protractor.conf.js
> +};
Can we add an extra line here 🙌

2020-11-16 11:33 UTC, carryall commented on karma.conf.js
> +    browsers: ['Chrome'],
How about changing this to `ChromeHeadless` ?

2020-11-16 11:33 UTC, carryall commented on e2e/protractor.conf.js
> +    browserName: 'chrome'
How about adding a chrome option here ?
```
chromeOptions: {
      args: ["--headless"]
    }
```

2020-11-17 03:16 UTC, Lahphim commented
@junan Should it be merged to `develop` branch instead of `main` branch?
![Screen Shot 2563-11-17 at 10 16 06](https://user-images.githubusercontent.com/749672/99342234-fc320a80-28bd-11eb-8b8c-fd5db156dd2c.png)

2020-11-17 03:39 UTC, Lahphim commented on package.json
> +    "@angular/animations": "~11.0.0",
@junan Should we install all these packages with specific version?

2020-11-17 03:39 UTC, Lahphim commented on src/app/app.component.html
> +<router-outlet></router-outlet>
@junan I think we need an tailing line.

2020-11-17 03:39 UTC, Lahphim commented on src/app/app.component.spec.ts
> +  it(`should have as title 'nimble-survey'`, () => {
@junan Should we keep `'` format?

2020-11-17 04:23 UTC, carryall approved these changes

2020-11-17 05:39 UTC, junan commented
> @junan Should it be merged to develop branch instead of main branch?
@Lahphim Done

2020-11-17 05:39 UTC, junan commented on src/app/app.component.spec.ts
> +  it(`should have as title 'nimble-survey'`, () => {
@Lahphim Done

2020-11-17 05:39 UTC, junan commented on src/app/app.component.html
> +<router-outlet></router-outlet>
@Lahphim Done

2020-11-17 05:39 UTC, junan commented on package.json
> +    "@angular/animations": "~11.0.0",
@Lahphim Done

2020-11-17 07:51 UTC, Lahphim approved these changes

2020-11-17 07:52 UTC, merged