Feature/login backend
junan/nimble-survey pull request #30
Opened 2020-12-22 07:25 UTC by junan

https://github.com/junan/nimble-survey/projects/1#card-50815162

## What happened

Describe the big picture of your changes here to communicate to the team why we should accept this pull request.

## Insight

## Proof of Work

Show us the implementation: screenshots, gif, etc.

2020-12-22 10:10 UTC, olivierobert requested changes
Not sure if it's good to add the survey list code in this PR already as it's out of scope 🤔 Maybe just the basic routing with no component rendering would do. Now there is some boilerplate for survey list which adds lots of files. Next time avoid doing so.

2020-12-22 10:10 UTC, olivierobert commented on src/app/shared/services/authentication/authentication.service.ts
> +    const endpoint = 'oauth/token';
As explained above, prefer adding the version here:

```suggestion
    const endpoint = 'v1/oauth/token';
```

There will be some repetition but it's more flexible.

2020-12-22 10:10 UTC, olivierobert commented on src/app/shared/services/authentication/authentication.service.spec.ts
> +      const request = httpMock.expectOne(`${environment.apiBaseUrl}/api/${environment.apiVersion}/oauth/token`);
``${environment.apiBaseUrl}/api/${environment.apiVersion}/oauth/token` could be stored in a variable to avoid repetition

2020-12-22 10:10 UTC, olivierobert commented on src/app/shared/constants.ts
> +  DEFAULT_ERROR_MESSAGE: 'Something went wrong. Please try again!',
For error messages, why not using [i18n](https://angular.io/guide/i18n) instead?

2020-12-22 10:10 UTC, olivierobert commented on src/app/modules/auth/components/form-sign-in/form-sign-in.component.ts
> +  onSubmit(data: string): void{
This method is currently not unit tested but should be

2020-12-22 10:10 UTC, olivierobert commented on src/app/modules/survey/pages/survey-list/survey-list.component.spec.ts
> +  it('should create', () => {
Prefer the imperative tone:

```suggestion
  it('renders the component', () => {
```

2020-12-22 10:10 UTC, olivierobert commented on src/app/shared/services/session/session.service.ts
> +    return localStorage.getItem(constants.USER_ACCESS_TOKEN_KEY) != null;
Alternative to do the same:

```suggestion
    return Boolean(localStorage.getItem(constants.USER_ACCESS_TOKEN_KEY));
```

Avoid doing as it's harder to read:

```suggestion
    return !!localStorage.getItem(constants.USER_ACCESS_TOKEN_KEY);
```

2020-12-23 07:49 UTC, olivierobert commented on .env.example
> +SIGN_IN_API_VERSION="v1"
My previous comment might have been not clear. IMO there is no need to have a constant for API versioning at all. This [comment](https://github.com/junan/nimble-survey/pull/30/files#r547182572) shows what I meant 😅

2020-12-23 09:12 UTC, junan commented on src/app/app.module.ts
> +import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
We need to add it when we use non angular component name with dash(`-`). I used `svg-icon-sprite` for svg css spite and we need call it `     <svg-icon  src="" ></svg-icon>`

Here is the doc for angular integration https://github.com/jannicz/svg-icon-sprite/blob/master/INTEGRATION.md#user-content-angular

2020-12-23 09:13 UTC, junan commented on src/app/modules/auth/components/form-sign-in/form-sign-in.component.ts
> +  onSubmit(data: string): void{
Added

2020-12-23 09:14 UTC, junan commented on .env.example
> +SIGN_IN_API_VERSION="v1"
Refactored 😄

2020-12-23 09:27 UTC, junan commented on src/locale/messages.xlf
> +<?xml version="1.0" encoding="UTF-8" ?>
Generated this file with `ng extract-i18n --output-path src/locale` command. For supporting new locale like `de`, we have to create new `messages.de.xlf` file here by manually copying this file content, then edit the content there.

2020-12-23 09:31 UTC, junan commented on src/app/shared/error-messages.ts
> +  INVALID_CREDENTIAL_ERROR_MESSAGE: $localize`:@@invalidCredentialError:Email or Password is invalid. Please try again.`,
`$localize` function is for localizing this text.  `@@invalidCredentialError` is for id to generate it in the [messages.xlf](https://github.com/junan/nimble-survey/pull/30/files#diff-db1a03e3781e595fd8985e7f0deb2201c3f15c507b620907ed0b4aacd5b2dd83R253) file

2020-12-24 04:35 UTC, olivierobert commented on src/app/app.module.ts
> +import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
Thanks for the link to the documentation

2020-12-24 04:41 UTC, olivierobert commented on src/app/shared/error-messages.ts
> +  INVALID_CREDENTIAL_ERROR_MESSAGE: $localize`:@@invalidCredentialError:Email or Password is invalid. Please try again.`,
What about localizing view components?

```
<label for="password" class="form-sign-in__label">Password</label>
```

I am not asking to do it in this PR, I just would like to know if the same can be used 💭

2020-12-24 04:42 UTC, olivierobert approved these changes
Looks good to me

In terms of process, make sure that the PR title matches the task title:

![image](https://user-images.githubusercontent.com/696529/103061179-12c63280-45dd-11eb-80cb-885d1d59478b.png)

So here it must be "[Backend] As a user I can log in #28"

2020-12-24 09:30 UTC, junan commented on src/app/shared/error-messages.ts
> +  INVALID_CREDENTIAL_ERROR_MESSAGE: $localize`:@@invalidCredentialError:Email or Password is invalid. Please try again.`,
Will do in a separate PR. Created the issue https://github.com/junan/nimble-survey/issues/36

2020-12-25 04:42 UTC, carryall commented on src/app/shared/services/authentication/authentication.service.ts
> +    const endpoint = 'v1/oauth/token';
@junan How about moving `v1` to an environment variable, what do you think?

2020-12-25 04:46 UTC, carryall commented on src/app/shared/services/guard/ensure-unautehnticated-user-guard.service.ts
> +
@junan How about removing the extra line here so the `@Injectable` class decorator stay right on top of the class 🙌🏼

2020-12-25 04:46 UTC, carryall commented on src/app/shared/services/session/session.service.ts
> +
@junan Same comment as above ☝🏼

2020-12-25 05:04 UTC, junan commented on src/app/shared/services/authentication/authentication.service.ts
> +    const endpoint = 'v1/oauth/token';
@carryall I initially added the API version in the `env` but Olivier suggested not to add it in the env as many different resources may have different version of api like `v1/login` and `v2/survey`. Here is related comments https://github.com/junan/nimble-survey/pull/30#discussion_r547767942, https://github.com/junan/nimble-survey/pull/30#discussion_r547182572

2020-12-25 05:27 UTC, carryall approved these changes

2020-12-25 05:36 UTC, merged